include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    prefer_final_locals: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
    - "rust_builder/**"
    - "ios/**"
    - "android/**"
    - "windows/**"
    - "macos/**"
  errors:
    invalid_annotation_target: ignore
